;(setq ergoemacs-theme "CUA")
;(setq ergoemacs-keyboard-layout "gb")
;(setq ergoemacs-command-loop-type nil)
;(require 'ergoemacs-mode)
;(load-file "~/.emacs.d/ergoemacs-custom-theme.el")
;(ergoemacs-mode 1)
