(require 'ergoemacs-functions)
(global-set-key (kbd "C-f") 'isearch-forward)
(global-set-key (kbd "C-o") 'find-file)
(global-set-key (kbd "C-s") 'save-buffer)
(global-set-key (kbd "C-w") 'ergoemacs-close-current-buffer)
(global-set-key (kbd "C-y") 'ergoemacs-redo)
(global-set-key (kbd "C-z") 'undo-tree-undo)
(global-set-key (kbd "<M-left>") 'ergoemacs-backward-open-bracket)
(global-set-key (kbd "<M-right>") 'ergoemacs-forward-close-bracket)
