(load-file "~/.emacs.d/configuration/init-modeline.el")
(set-face-attribute 'powerline-active1 nil :background "yellow" :foreground "black")
(set-face-attribute 'powerline-active2 nil :background "white")
(set-face-attribute 'powerline-inactive1 nil :background "yellow4" :foreground "black")
(set-face-attribute 'powerline-inactive2 nil :background "dim grey")
