(purpose-mode)
(require 'window-purpose-x)
(purpose-x-magit-single-on)
(add-to-list 'purpose-user-mode-purposes '(org-mode . org))
(add-to-list 'purpose-user-mode-purposes '(org-agenda-mode . org))
(purpose-compile-user-configuration)
