(require 'org)
(define-key global-map "\C-cl" 'org-store-link)
(define-key global-map "\C-ca" 'org-agenda)
(setq org-log-done t)
(setq org-agenda-window-setup 'same-window)
(setq org-todo-keywords
      '((sequence "TODO" "INPROGRESS" "WAITING" "|" "DONE" "CANCELLED")))
(setq org-agenda-files '("~/org"))
(setq org-agenda-prefix-format
      '((agenda . " %i %-12:c%?-12t% s")
        (timeline . "  % s")
        (todo . " %i %-6:c%l")
        (tags . " %i %-12:c")
        (search . " %i %-12:c")))
(defun startup-todolist ()
  (org-todo-list t)
 )
(add-hook 'window-setup-hook 'startup-todolist)
